### ISSUE TITLE
white spaces on 'albumArtist'

### ISSUE THREAD

**Issue by angmyu** [newgiin/cloudplayer-scrobbler#18] opened 2015-01-21 05:10 UTC
From recent update, there are some issues on 'albumArtist' string processing.
For example, I would scrobble 'The Tetra' by 'Alan Fitzpatrick':

http://www.last.fm/music/Alan%252BFitzpatrick/The+Tetra

Now, scrobbler sends like above 'Alan+Fitzpatrick,' so it is recognized as new item, which is completely different with proper following:

http://www.last.fm/music/Alan+Fitzpatrick/The+Tetra

I think It should be fixed quickly. Every track which contains white space in (album) artist name is making scrobble history hell right now.
Further, It would be good to be selectable, for which the user scrobbles by album artist or not.
Thanks.

**Comment by newgiin** [comment] 2015-01-21 07:25
Woops, sorry didn't have much time to test this. Fixed in version 1.6.0.

What is the motive for making it selectable? Album artist seems to only be used by last.fm to determine what album is being played (to differentiate with other albums of the same name), otherwise it uses the artist for your artist history.

**Comment by angmyu** [comment] 2015-01-21 09:43
@newgiin 
Thanks for fast fix, but it still has bug.
Please check following 'Blasterjaxx &+DBSTF' and 'Armin van+Buuren':

Wrong: http://www.last.fm/music/Blasterjaxx+&%252BDBSTF/Beautiful+World
Correct: http://www.last.fm/music/Blasterjaxx+&+DBSTF/Beautiful+World

Wrong: http://www.last.fm/music/Armin+van%252BBuuren/Together+%28In+A+State+Of+Trance%29
Correct: http://www.last.fm/music/Armin+van+Buuren/Together+%28In+A+State+Of+Trance%29

Still, many other scrobbler doesn't support scrobbling 'album artist' because it is officially an option of track submission method in API. So it may be confused for making  statistics by using with other scrobbler in different environment (e.g. Mobile or PC;foobar2000, etc.) Well, it may be kinda trivial thing but I think someone may cares.

Anyway, big thanks for your volunteer! I really appreciate it!

**Comment by newgiin** [comment] 2015-01-23 18:06
For those cases, it is working as intended because if there is a '+' in the artist name, it is going to get sent as a '+'. For example, +44: http://www.last.fm/music/%252B44. I think I will just keep it as is because I even if some scrobblers don't use the album artist, using it will always be better for your stats as it's the official way albums are categorized by last.fm.

**Comment by angmyu** [comment] 2015-01-25 09:49
@newgiin 
I think you misunderstood. there are no actual '+' in artist name on those examples of mine.
Proper name is 'Armin van Buuren', not 'Armin van+Buuren'.
It is obviously wrongly scrobbled and I think it must be fixed.
I can see that, when the 'album artist name' has more than 2 white spaces, It does not properly convert its second space, and third, and so on.

Of course, there is no problem in the case of the artist name has '+', as your example '+44' because there are no space. However, I also confirmed misbehavior in my case as following:

'Dillon Francis & Sultan + Ned Shepard feat. The Chain Gang Of 1974'

It must be scrobbled as this proper album:
http://www.last.fm/music/Dillon+Francis+&+Sultan+%252B+Ned+Shepard+Feat.+The+Chain+Gang+Of+1974/When+We+Were+Young+%28Remixes%29

However, your scrobbler scrobbles as following wrong:
http://www.last.fm/music/Dillon+Francis%252B&%252BSultan%252B%252B%252BNed%252BShepard%252Bfeat.%252BThe%252BChain%252BGang%252BOf%252B1974/When+We+Were+Young+%28Remixes%29

You can see how it is wrongly scrobbled.

Btw, I see that you will keep 'scrobbling album artist' as a built in default and not as an selectable option. I agree that this is more precise categorization with official last.fm way if the above bug is completely solved.

Thanks!

**Comment by newgiin** [comment] 2015-01-25 21:55
Ahh, yeah, I see now. A new version has been pushed, 1.6.1 should fix it. 

8cf23b7947c9737fa7e96833561e710216d372fb

**Closed as completed by newgiin** 2015-01-25 21:55 UTC

**Comment by angmyu** [comment] 2015-01-26 03:02
Now it works fine! Big thanks!!!
